name: Dynamic README injection
on:
  schedule: # Run workflow automatically
    # This will make it run every hour
    - cron: "0 * * * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

jobs:
  get-reddit-meme:
    environment: Reddit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Update README
        run: yarn update
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}

      - name: Commit changes
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "reddit-meme-bot"
          git config --global user.email "contact@zeyu2001.com"
          git commit --allow-empty -m "[Automated] README updated with new meme!"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
